INSERT INTO ACCOUNTS (ID, ACCOUNT_NAME) VALUES (1, 'USA');
INSERT INTO ACCOUNTS (ID, ACCOUNT_NAME) VALUES (2, 'France');
INSERT INTO ACCOUNTS (ID, ACCOUNT_NAME) VALUES (3, 'Brazil');
INSERT INTO ACCOUNTS (ID, ACCOUNT_NAME) VALUES (4, 'Italy');
INSERT INTO ACCOUNTS (ID, ACCOUNT_NAME) VALUES (5, 'Canada');