-- Users table
INSERT INTO USERS (USER_ID, USER_NAME) VALUES ('1', 'VIKRAM');

-- Accounts table
INSERT INTO ACCOUNTS (ACCOUNT_NUMBER, USER_ID, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE_DATE, CURRENCY, OPENING_AVAILABLE_BALANCE) VALUES ('585309209', '1', 'SGSavings726', 'Savings', PARSEDATETIME('08/11/2018', 'dd/MM/yyyy'), 'SGD', 84327.51);

-- Transactions table
INSERT INTO TRANSACTIONS (TX_ID, ACCOUNT_NUMBER, VALUE_DATE, AMOUNT, TRANSACTION_TYPE, TRANSACTION_NARRATIVE) VALUES ('1', '585309209', PARSEDATETIME('02/01/2012', 'dd/MM/yyyy'), 9540.98, 'CREDIT', '');

